# project info
site_name: Crypto Notes
site_description: 'My notes on cryptocurrencies'
site_author: 'Jordan McKinney'
site_url: 'https://jordanmmck.com/crypto_notes'

# repo
repo_name: 'jordanmmck/crypto_notes'
repo_url: 'https://github.com/jordanmmck/crypto_notes'

# theme
theme: material
site_favicon: 'img/favicon.png'

# layout
docs_dir: Notes
pages:
- Home: 'index.md'
- Basic Tech:
    - 'Hashing': 'basic_tech/hashing.md'
    - 'Public Key Crypto': 'basic_tech/pubkey.md'
    - 'Blockchains': 'basic_tech/blockchain.md'
- Cryptoeconomics:
    - 'Markets': 'cryptoeconomics/markets.md'
    - 'Money': 'cryptoeconomics/money.md'
    - 'Networks': 'cryptoeconomics/networks.md'

# options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/jordanmmck'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jordanmmckinney'
