# project info
site_name: Crypto Notes
site_description: 'My notes on cryptocurrencies'
site_author: 'Jordan McKinney'
site_url: 'https://jordanmmck.com/blockchain'

# repo
repo_name: 'jordanmmck/blockchain'
repo_url: 'https://github.com/jordanmmck/blockchain'

# theme
theme: readthedocs
site_favicon: 'img/favicon.png'

# layout
docs_dir: Notes
pages:
- Home: 'index.md'
- Basic Tech:
    - 'Hashing': 'basic_tech/hashing.md'
    - 'Public Key Crypto': 'basic_tech/pubkey.md'
    - 'Blockchains': 'basic_tech/blockchain.md'
- Cryptoeconomics:
    - 'Markets': 'cryptoeconomics/markets.md'
    - 'Money': 'cryptoeconomics/money.md'
    - 'Networks': 'cryptoeconomics/networks.md'
- Cryptocurrencies High-level:
    - 'Two Generals Problem': 'crypto_highlevel/byzantine.md'
    - 'Sybil Attacks': 'crypto_highlevel/sybil.md'
- Applications:
    - 'Notable Projects': 'applications/projects.md'
    - 'Decentralized Internet': 'applications/dec_internet.md'
    - 'Decentralized Storage': 'applications/dec_storage.md'
    - 'Decentralized Computing': 'applications/dec_compute.md'

# options
extra:
  social:
    - type: 'github'
      link: 'https://github.com/jordanmmck'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jordanmmckinney'
